export const CATEGORIES = [
  { id: 'all',      label: 'All Tools', icon: '⚡' },
  { id: 'organize', label: 'Organize',  icon: '📂' },
  { id: 'optimize', label: 'Optimize',  icon: '⚙️' },
  { id: 'convert',  label: 'Convert',   icon: '🔄' },
  { id: 'security', label: 'Security',  icon: '🔐' },
  { id: 'intel',    label: 'Intel',     icon: '🧠' },
];

export const TOOLS = [
  // ── ORGANIZE ────────────────────────────────────────────────────────────────
  {
    id: 'merge',
    category: 'organize',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one document. Drag to reorder pages before merging.',
    icon: '🔗',
    gradient: 'from-blue-500 to-indigo-600',
    accent: '#6060ef',
    endpoint: '/api/v1/pdf/organize/merge',
    multiFile: true,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'orderIndices', label: 'Custom Order', type: 'hidden', default: null },
    ],
  },
  {
    id: 'split',
    category: 'organize',
    title: 'Split PDF',
    description: 'Extract specific page ranges or split every page into individual files.',
    icon: '✂️',
    gradient: 'from-violet-500 to-purple-600',
    accent: '#8b5cf6',
    endpoint: '/api/v1/pdf/organize/split',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'mode', label: 'Split Mode', type: 'select', options: ['range', 'all'], default: 'range' },
      { key: 'ranges', label: 'Page Ranges', type: 'text', placeholder: 'e.g. 1-3, 5, 7-9', default: '' },
    ],
  },
  {
    id: 'remove-pages',
    category: 'organize',
    title: 'Remove Pages',
    description: 'Delete specific pages from a PDF document by page number.',
    icon: '🗑️',
    gradient: 'from-rose-500 to-red-600',
    accent: '#ef4444',
    endpoint: '/api/v1/pdf/organize/remove-pages',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'pageIndices', label: 'Pages to Remove', type: 'text', placeholder: 'e.g. 1, 3-5, 8', default: '' },
    ],
  },
  {
    id: 'extract-pages',
    category: 'organize',
    title: 'Extract Pages',
    description: 'Isolate and extract specific pages from a PDF into a new document.',
    icon: '📄',
    gradient: 'from-cyan-500 to-blue-600',
    accent: '#06b6d4',
    endpoint: '/api/v1/pdf/organize/extract-pages',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'pageIndices', label: 'Pages to Extract', type: 'text', placeholder: 'e.g. 1-4, 6', default: '' },
    ],
  },
  {
    id: 'reorder',
    category: 'organize',
    title: 'Reorder Pages',
    description: 'Rearrange pages in any sequence using an explicit index mutation array.',
    icon: '↕️',
    gradient: 'from-teal-500 to-emerald-600',
    accent: '#10b981',
    endpoint: '/api/v1/pdf/organize/reorder',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'newOrder', label: 'New Page Order', type: 'text', placeholder: 'e.g. 3, 1, 2, 4-6', default: '' },
    ],
  },

  // ── OPTIMIZE ────────────────────────────────────────────────────────────────
  {
    id: 'compress',
    category: 'optimize',
    title: 'Compress PDF',
    description: 'Reduce file size with three compression tiers: Low, Medium, and High density.',
    icon: '🗜️',
    gradient: 'from-amber-500 to-orange-600',
    accent: '#f59e0b',
    endpoint: '/api/v1/pdf/optimize/compress',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'tier', label: 'Compression Level', type: 'select', options: ['low', 'medium', 'high'], default: 'medium' },
    ],
  },
  {
    id: 'repair',
    category: 'optimize',
    title: 'Repair PDF',
    description: 'Recover broken cross-reference tables (XREFs) in corrupted PDF files.',
    icon: '🔧',
    gradient: 'from-slate-500 to-gray-700',
    accent: '#64748b',
    endpoint: '/api/v1/pdf/optimize/repair',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [],
  },

  // ── CONVERT ─────────────────────────────────────────────────────────────────
  {
    id: 'image-to-pdf',
    category: 'convert',
    title: 'Image to PDF',
    description: 'Convert JPG, PNG, WebP, or TIFF images into a professional PDF document.',
    icon: '🖼️',
    gradient: 'from-pink-500 to-rose-600',
    accent: '#ec4899',
    endpoint: '/api/v1/pdf/convert/image-to-pdf',
    multiFile: false,
    acceptedFiles: { 'image/*': ['.jpg', '.jpeg', '.png', '.webp', '.tiff', '.gif'] },
    wasmEligible: false,
    configSchema: [],
  },
  {
    id: 'html-to-pdf',
    category: 'convert',
    title: 'HTML to PDF',
    description: 'Convert HTML documents or raw HTML strings into PDF format.',
    icon: '🌐',
    gradient: 'from-orange-500 to-amber-600',
    accent: '#f97316',
    endpoint: '/api/v1/pdf/convert/html-to-pdf',
    multiFile: false,
    acceptedFiles: { 'text/html': ['.html', '.htm'] },
    wasmEligible: false,
    configSchema: [
      {
        key: 'conversionMode',
        label: 'Conversion Mode',
        type: 'select',
        options: ['Code PDF', 'GUI Output PDF', 'Summary Output PDF'],
        default: 'GUI Output PDF'
      }
    ],
  },
  {
    id: 'word-to-pdf',
    category: 'convert',
    title: 'Word to PDF',
    description: 'Convert Microsoft Word documents (.docx) to PDF format.',
    icon: '📝',
    gradient: 'from-blue-600 to-cyan-600',
    accent: '#2563eb',
    endpoint: '/api/v1/pdf/convert/word-to-pdf',
    multiFile: false,
    acceptedFiles: { 'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'] },
    wasmEligible: false,
    configSchema: [],
    badge: 'Requires LibreOffice',
  },
  {
    id: 'excel-to-pdf',
    category: 'convert',
    title: 'Excel to PDF',
    description: 'Convert Microsoft Excel spreadsheets (.xlsx) to PDF format.',
    icon: '📊',
    gradient: 'from-green-600 to-emerald-600',
    accent: '#16a34a',
    endpoint: '/api/v1/pdf/convert/excel-to-pdf',
    multiFile: false,
    acceptedFiles: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] },
    wasmEligible: false,
    configSchema: [],
    badge: 'Requires LibreOffice',
  },
  {
    id: 'pdf-to-word',
    category: 'convert',
    title: 'PDF to Word',
    description: 'Extract text from PDF and generate a .docx Word document. Supports OCR for scanned PDFs.',
    icon: '📃',
    gradient: 'from-sky-500 to-blue-600',
    accent: '#0ea5e9',
    endpoint: '/api/v1/pdf/convert/pdf-to-word',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'ocr', label: 'Enable OCR for scanned PDFs', type: 'toggle', default: false },
    ],
  },
  {
    id: 'pdf-to-excel',
    category: 'convert',
    title: 'PDF to Excel',
    description: 'Parse PDF text into structured Excel grids. Activate OCR to handle scanned tables.',
    icon: '📈',
    gradient: 'from-emerald-500 to-green-600',
    accent: '#10b981',
    endpoint: '/api/v1/pdf/convert/pdf-to-excel',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'ocr', label: 'Enable OCR for scanned PDFs', type: 'toggle', default: false },
    ],
  },
  {
    id: 'pdf-to-jpg',
    category: 'convert',
    title: 'PDF to JPG',
    description: 'Convert PDF pages to high-quality JPEG images (manifest mode — renderer sidecar for full output).',
    icon: '📸',
    gradient: 'from-fuchsia-500 to-pink-600',
    accent: '#d946ef',
    endpoint: '/api/v1/pdf/convert/pdf-to-jpg',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [],
  },
  {
    id: 'pdf-to-pdfa',
    category: 'convert',
    title: 'PDF to PDF/A',
    description: 'Convert standard PDFs to archival PDF/A-1b format with embedded metadata.',
    icon: '🗄️',
    gradient: 'from-indigo-500 to-violet-600',
    accent: '#6366f1',
    endpoint: '/api/v1/pdf/convert/pdf-to-pdfa',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [],
  },

  // ── SECURITY ────────────────────────────────────────────────────────────────
  {
    id: 'protect',
    category: 'security',
    title: 'Protect PDF',
    description: 'Encrypt PDF with owner and user passwords and granular permission flags.',
    icon: '🔒',
    gradient: 'from-red-500 to-rose-600',
    accent: '#ef4444',
    endpoint: '/api/v1/pdf/security/protect',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'ownerPassword', label: 'Owner Password', type: 'password', placeholder: 'Strong owner password', default: '' },
      { key: 'userPassword',  label: 'User Password',  type: 'password', placeholder: 'User open password',   default: '' },
    ],
  },
  {
    id: 'unlock',
    category: 'security',
    title: 'Unlock PDF',
    description: 'Remove password protection and permission flags from encrypted PDFs.',
    icon: '🔓',
    gradient: 'from-yellow-500 to-orange-500',
    accent: '#eab308',
    endpoint: '/api/v1/pdf/security/unlock',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'password', label: 'PDF Password', type: 'password', placeholder: 'Enter password to unlock', default: '' },
    ],
  },
  {
    id: 'watermark',
    category: 'security',
    title: 'Watermark PDF',
    description: 'Stamp persistent text or logo watermarks on all pages with opacity control.',
    icon: '💧',
    gradient: 'from-cyan-500 to-teal-600',
    accent: '#06b6d4',
    endpoint: '/api/v1/pdf/security/watermark',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: true,
    configSchema: [
      { key: 'text',     label: 'Watermark Text', type: 'text',   placeholder: 'e.g. CONFIDENTIAL', default: 'CONFIDENTIAL' },
      { key: 'opacity',  label: 'Opacity',         type: 'slider', min: 0.05, max: 0.5, step: 0.05, default: 0.15 },
      { key: 'fontSize', label: 'Font Size',        type: 'number', min: 20, max: 80,               default: 48 },
      { key: 'position', label: 'Position',         type: 'select', options: ['diagonal', 'center', 'top', 'bottom'], default: 'diagonal' },
    ],
  },
  {
    id: 'compare',
    category: 'security',
    title: 'Compare PDFs',
    description: 'Run a structural layout comparison between two PDFs and get a differential map.',
    icon: '⚖️',
    gradient: 'from-violet-500 to-indigo-600',
    accent: '#7c3aed',
    endpoint: '/api/v1/pdf/security/compare',
    multiFile: true,
    maxFiles: 2,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [],
  },
  {
    id: 'sign',
    category: 'security',
    title: 'Sign PDF',
    description: 'Inject visible signature overlays at absolute coordinates on specified pages.',
    icon: '✍️',
    gradient: 'from-blue-500 to-indigo-600',
    accent: '#3b82f6',
    endpoint: '/api/v1/pdf/security/sign',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'text', label: 'Signature Text', type: 'text',   placeholder: 'Your Name / Signature', default: '' },
      { key: 'page', label: 'Page Number',    type: 'number', min: 1,  default: 1 },
      { key: 'x',    label: 'X Position (pts)', type: 'number', min: 0, default: 50 },
      { key: 'y',    label: 'Y Position (pts)', type: 'number', min: 0, default: 50 },
    ],
  },
  {
    id: 'auto-redact',
    category: 'security',
    title: 'Auto Redact',
    description: 'Automatically detect and hard-mask PII (Aadhaar, PAN, emails, phones) with black rectangles.',
    icon: '🕵️',
    gradient: 'from-gray-600 to-slate-800',
    accent: '#374151',
    endpoint: '/api/v1/pdf/security/auto-redact',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      {
        key: 'patterns',
        label: 'PII Patterns',
        type: 'multicheck',
        options: ['Aadhaar', 'PAN', 'Email', 'Phone_IN', 'Phone_US', 'SSN', 'CreditCard', 'Passport_IN'],
        default: [],
      },
    ],
    badge: 'AI Powered',
  },

  // ── INTEL ───────────────────────────────────────────────────────────────────
  {
    id: 'summarize',
    category: 'intel',
    title: 'Summarize PDF',
    description: 'Extract key sentences and top keywords to generate a structured document summary.',
    icon: '📋',
    gradient: 'from-emerald-500 to-teal-600',
    accent: '#10b981',
    endpoint: '/api/v1/pdf/intel/summarize',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'sentences', label: 'Key Sentences Count', type: 'number', min: 3, max: 20, default: 5 },
    ],
  },
  {
    id: 'translate',
    category: 'intel',
    title: 'Translate PDF',
    description: 'Extract paragraphs and structure them for translation API integration.',
    icon: '🌍',
    gradient: 'from-sky-500 to-cyan-600',
    accent: '#0ea5e9',
    endpoint: '/api/v1/pdf/intel/translate',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [
      { key: 'targetLanguage', label: 'Target Language', type: 'select', options: ['es', 'fr', 'de', 'hi', 'zh', 'ar', 'pt', 'ja'], default: 'es' },
    ],
  },
  {
    id: 'forms-detector',
    category: 'intel',
    title: 'Forms Detector',
    description: 'Analyze PDF layout to automatically identify form field bounding boxes and interactive elements.',
    icon: '📝',
    gradient: 'from-amber-500 to-yellow-600',
    accent: '#f59e0b',
    endpoint: '/api/v1/pdf/intel/forms-detector',
    multiFile: false,
    acceptedFiles: { 'application/pdf': ['.pdf'] },
    wasmEligible: false,
    configSchema: [],
  },
];

/**
 * Get a single tool definition by its ID.
 * @param {string} id
 * @returns {object|null}
 */
export function getToolById(id) {
  return TOOLS.find(t => t.id === id) || null;
}

/**
 * Get all tools belonging to a category.
 * @param {string} category
 * @returns {object[]}
 */
export function getToolsByCategory(category) {
  if (category === 'all') return TOOLS;
  return TOOLS.filter(t => t.category === category);
}
